source: asr
events:
- time: 0.0
  gesture: 张开
- time: 15.19
  gesture: 壹
- time: 15.54
  gesture: 贰
- time: 16.04
  gesture: 叁
- time: 16.36
  gesture: 肆
- time: 16.86
  gesture: 伍
- time: 17.36
  gesture: 陆
- time: 17.82
  gesture: 柒
- time: 18.22
  gesture: 捌
- time: 18.74
  gesture: 贰
- time: 19.16
  gesture: 贰
- time: 19.64
  gesture: 叁
- time: 20.06
  gesture: 肆
- time: 20.54
  gesture: 伍
- time: 20.98
  gesture: 陆
- time: 21.42
  gesture: 柒
- time: 21.84
  gesture: 捌
- time: 22.4
  gesture: 叁
- time: 22.74
  gesture: 贰
- time: 22.82
  gesture: 叁
- time: 23.38
  gesture: 肆
- time: 23.76
  gesture: 伍
- time: 24.28
  gesture: 陆
- time: 24.72
  gesture: 柒
- time: 25.16
  gesture: 捌
- time: 25.6
  gesture: 肆
- time: 26.14
  gesture: 贰
- time: 26.5
  gesture: 叁
- time: 27.02
  gesture: 肆
- time: 27.4
  gesture: 伍
- time: 27.92
  gesture: 陆
- time: 29.52
  gesture: 壹
- time: 29.94
  gesture: 贰
- time: 30.24
  gesture: 叁
- time: 30.72
  gesture: 肆
- time: 31.14
  gesture: 伍
- time: 31.64
  gesture: 张开
