source: asr_05x
events:
- time: 0.0
  gesture: 张开
- time: 30.38
  gesture: 壹
- time: 31.08
  gesture: 贰
- time: 32.08
  gesture: 叁
- time: 32.72
  gesture: 肆
- time: 33.72
  gesture: 伍
- time: 34.72
  gesture: 陆
- time: 35.64
  gesture: 柒
- time: 36.44
  gesture: 捌
- time: 37.48
  gesture: 贰
- time: 38.32
  gesture: 贰
- time: 39.28
  gesture: 叁
- time: 40.12
  gesture: 肆
- time: 41.08
  gesture: 伍
- time: 41.96
  gesture: 陆
- time: 42.84
  gesture: 柒
- time: 43.68
  gesture: 捌
- time: 44.8
  gesture: 叁
- time: 45.48
  gesture: 贰
- time: 45.64
  gesture: 叁
- time: 46.76
  gesture: 肆
- time: 47.52
  gesture: 伍
- time: 48.56
  gesture: 陆
- time: 49.44
  gesture: 柒
- time: 50.32
  gesture: 捌
- time: 51.2
  gesture: 肆
- time: 52.28
  gesture: 贰
- time: 53.0
  gesture: 叁
- time: 54.04
  gesture: 肆
- time: 54.8
  gesture: 伍
- time: 55.84
  gesture: 陆
- time: 59.04
  gesture: 壹
- time: 59.88
  gesture: 贰
- time: 60.48
  gesture: 叁
- time: 61.44
  gesture: 肆
- time: 62.28
  gesture: 伍
- time: 63.28
  gesture: 张开
